### PR TITLE
Fix link and header

### PR DESCRIPTION
**Pull request by sinacek**
Hi Marian, thanks for sharing. I would like just fix link and one header.

### CODE REVIEW

**Review by marian-kamenistak — APPROVED** [review]
Approved, Thanks @sinacek

**Comment by sinacek** [comment]
I dont have access to merge it, could you do it please?

**Comment by sinacek** [comment]
@marian-kamenistak I dont have access to merge it, could you do it please?

**Comment by sinacek** [comment]
@marian-kamenistak could you merge it? 
```
Only those with write access to this repository can merge pull requests.
```

**Comment by marian-kamenistak** [comment]
František Hána

**Pull request merged**
